version: '3.8'

services:
  postgres:
    image: postgres
    container_name: fractal-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fractal-net

volumes:
  postgres-data:

networks:
  fractal-net: